# Google 股價為範例，操作時間序列的技巧

In [29]:
import pandas as pd
import datetime as dt
import pandas_datareader.data as data

# 舊程式碼
# start = dt.datetime(2020, 3, 1)
# end = dt.datetime(2020, 4, 30)
# df = data.get_data_yahoo('GOOG', start, end) ('股票名稱','起始時間','結束時間')
# df

# 更新後的程式碼
df = data.DataReader('AAPL', data_source = 'stooq', start='2022-11-01',end='2022-12-31')
df

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-11-01,155.080002,155.449997,149.130005,150.649994,150.400497,80379300
2022-11-02,148.949997,152.169998,145.000000,145.029999,144.789810,93604600
2022-11-03,142.059998,142.800003,138.750000,138.880005,138.650009,97918500
2022-11-04,142.089996,142.669998,134.380005,138.380005,138.380005,140814800
2022-11-07,137.110001,139.149994,135.669998,138.919998,138.919998,83374600
2022-11-08,140.410004,141.429993,137.490005,139.500000,139.500000,89908500
2022-11-09,138.500000,138.550003,134.589996,134.869995,134.869995,74917800
2022-11-10,141.240005,146.869995,139.500000,146.869995,146.869995,118854000
2022-11-11,145.820007,150.009995,144.369995,149.699997,149.699997,93979700
2022-11-14,148.970001,150.279999,147.429993,148.279999,148.279999,73374100
2022-11-15,152.220001,153.589996,148.559998,150.039993,150.039993,89868300
2022-11-16,149.130005,149.869995,147.289993,148.789993,148.789993,64218300
2022-11-17,146.429993,151.479996,146.149994,150.720001,150.720001,80389400
2022-11-18,152.309998,152.699997,149.970001,151.289993,151.289993,74829600
2022-11-21,150.160004,150.369995,147.720001,148.009995,148.009995,58724100
2022-11-22,148.130005,150.419998,146.929993,150.179993,150.179993,51804100
2022-11-23,149.449997,151.830002,149.339996,151.070007,151.070007,58301400
2022-11-25,148.309998,148.880005,147.119995,148.110001,148.110001,35195900
2022-11-28,145.139999,146.639999,143.380005,144.220001,144.220001,69246000
2022-11-29,144.289993,144.809998,140.350006,141.169998,141.169998,83763800
2022-11-30,141.399994,148.720001,140.550003,148.029999,148.029999,111380900
2022-12-01,148.210007,149.130005,146.610001,148.309998,148.309998,71250400
2022-12-02,145.960007,148.000000,145.649994,147.809998,147.809998,65447400
2022-12-05,147.770004,150.919998,145.770004,146.630005,146.630005,68826400
2022-12-06,147.070007,147.300003,141.919998,142.910004,142.910004,64727200
2022-12-07,142.190002,143.369995,140.000000,140.940002,140.940002,69721100
2022-12-08,142.360001,143.520004,141.100006,142.649994,142.649994,62128300
2022-12-09,142.339996,145.570007,140.899994,142.160004,142.160004,76097000
2022-12-12,142.699997,144.500000,141.059998,144.490005,144.490005,70462700
2022-12-13,149.500000,149.970001,144.240005,145.470001,145.470001,93886200
2022-12-14,145.350006,146.660004,141.160004,143.210007,143.210007,82291200
2022-12-15,141.110001,141.800003,136.029999,136.500000,136.500000,98931900
2022-12-16,136.690002,137.649994,133.729996,134.509995,134.509995,160156900
2022-12-19,135.110001,135.199997,131.320007,132.369995,132.369995,79592600
2022-12-20,131.389999,133.250000,129.889999,132.300003,132.300003,77432800
2022-12-21,132.979996,136.809998,132.750000,135.449997,135.449997,85928000
2022-12-22,134.350006,134.559998,130.300003,132.229996,132.229996,77852100
2022-12-23,130.919998,132.419998,129.639999,131.860001,131.860001,63814900
2022-12-27,131.380005,131.410004,128.720001,130.029999,130.029999,69007800
2022-12-28,129.669998,131.029999,125.870003,126.040001,126.040001,85438400
2022-12-29,127.989998,130.479996,127.730003,129.610001,129.610001,75703700
2022-12-30,128.410004,129.949997,127.430000,129.929993,129.929993,76960600

## DatetimeIndex
用時間作為索引的型態<br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html

In [30]:
#不是使用'Date'欄位名稱，使用index，是一個 DatetimeIndex物件，week為屬性
#返回每個日期所属的週數
df.index.week

<ipython-input-30-1397a0ba33b2>:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  df.index.week

Int64Index([44, 44, 44, 44, 45, 45, 45, 45, 45, 46, 46, 46, 46, 46, 47, 47, 47,
            47, 48, 48, 48, 48, 48, 49, 49, 49, 49, 49, 50, 50, 50, 50, 50, 51,
            51, 51, 51, 51, 52, 52, 52, 52],
           dtype='int64', name='Date')

## 計算每週交易量總和

In [31]:
df['week'] = df.index.week
df

<ipython-input-31-fcd2fc349e0e>:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  df['week'] = df.index.week

,Open,High,Low,Close,Adj Close,Volume,week
Date,,,,,,,
2022-11-01,155.080002,155.449997,149.130005,150.649994,150.400497,80379300,44
2022-11-02,148.949997,152.169998,145.000000,145.029999,144.789810,93604600,44
2022-11-03,142.059998,142.800003,138.750000,138.880005,138.650009,97918500,44
2022-11-04,142.089996,142.669998,134.380005,138.380005,138.380005,140814800,44
2022-11-07,137.110001,139.149994,135.669998,138.919998,138.919998,83374600,45
2022-11-08,140.410004,141.429993,137.490005,139.500000,139.500000,89908500,45
2022-11-09,138.500000,138.550003,134.589996,134.869995,134.869995,74917800,45
2022-11-10,141.240005,146.869995,139.500000,146.869995,146.869995,118854000,45
2022-11-11,145.820007,150.009995,144.369995,149.699997,149.699997,93979700,45
2022-11-14,148.970001,150.279999,147.429993,148.279999,148.279999,73374100,46
2022-11-15,152.220001,153.589996,148.559998,150.039993,150.039993,89868300,46
2022-11-16,149.130005,149.869995,147.289993,148.789993,148.789993,64218300,46
2022-11-17,146.429993,151.479996,146.149994,150.720001,150.720001,80389400,46
2022-11-18,152.309998,152.699997,149.970001,151.289993,151.289993,74829600,46
2022-11-21,150.160004,150.369995,147.720001,148.009995,148.009995,58724100,47
2022-11-22,148.130005,150.419998,146.929993,150.179993,150.179993,51804100,47
2022-11-23,149.449997,151.830002,149.339996,151.070007,151.070007,58301400,47
2022-11-25,148.309998,148.880005,147.119995,148.110001,148.110001,35195900,47
2022-11-28,145.139999,146.639999,143.380005,144.220001,144.220001,69246000,48
2022-11-29,144.289993,144.809998,140.350006,141.169998,141.169998,83763800,48
2022-11-30,141.399994,148.720001,140.550003,148.029999,148.029999,111380900,48
2022-12-01,148.210007,149.130005,146.610001,148.309998,148.309998,71250400,48
2022-12-02,145.960007,148.000000,145.649994,147.809998,147.809998,65447400,48
2022-12-05,147.770004,150.919998,145.770004,146.630005,146.630005,68826400,49
2022-12-06,147.070007,147.300003,141.919998,142.910004,142.910004,64727200,49
2022-12-07,142.190002,143.369995,140.000000,140.940002,140.940002,69721100,49
2022-12-08,142.360001,143.520004,141.100006,142.649994,142.649994,62128300,49
2022-12-09,142.339996,145.570007,140.899994,142.160004,142.160004,76097000,49
2022-12-12,142.699997,144.500000,141.059998,144.490005,144.490005,70462700,50
2022-12-13,149.500000,149.970001,144.240005,145.470001,145.470001,93886200,50
2022-12-14,145.350006,146.660004,141.160004,143.210007,143.210007,82291200,50
2022-12-15,141.110001,141.800003,136.029999,136.500000,136.500000,98931900,50
2022-12-16,136.690002,137.649994,133.729996,134.509995,134.509995,160156900,50
2022-12-19,135.110001,135.199997,131.320007,132.369995,132.369995,79592600,51
2022-12-20,131.389999,133.250000,129.889999,132.300003,132.300003,77432800,51
2022-12-21,132.979996,136.809998,132.750000,135.449997,135.449997,85928000,51
2022-12-22,134.350006,134.559998,130.300003,132.229996,132.229996,77852100,51
2022-12-23,130.919998,132.419998,129.639999,131.860001,131.860001,63814900,51
2022-12-27,131.380005,131.410004,128.720001,130.029999,130.029999,69007800,52
2022-12-28,129.669998,131.029999,125.870003,126.040001,126.040001,85438400,52
2022-12-29,127.989998,130.479996,127.730003,129.610001,129.610001,75703700,52
2022-12-30,128.410004,129.949997,127.430000,129.929993,129.929993,76960600,52

In [32]:
df.groupby('week').Volume.sum()

week
44    412717200
45    461034600
46    382679700
47    204025500
48    401088500
49    341500000
50    505728900
51    384620400
52    307110500
Name: Volume, dtype: int64

## resample
調整週期重新採樣的方法<br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html#pandas.DataFrame.resample

In [33]:
ten = df.resample('10D').mean()
ten

,Open,High,Low,Close,Adj Close,Volume,week
Date,,,,,,,
2022-11-01,143.180000,144.886248,139.313751,141.637499,141.547539,9.747151e+07,44.500000
2022-11-11,149.146667,151.321663,147.294996,149.803329,149.803329,7.944323e+07,45.833333
2022-11-21,146.697141,148.810000,145.055714,147.255713,147.255713,6.691660e+07,47.428571
2022-12-01,145.128575,146.830002,143.135714,144.487143,144.487143,6.831397e+07,48.714286
2022-12-11,140.264287,141.290000,136.775715,138.407144,138.407144,9.467919e+07,50.285714
2022-12-21,130.814286,132.379998,128.920001,130.735712,130.735712,7.638650e+07,51.571429